### ISSUE TITLE
[BUG]知识库描述设置2个字符导致think容器退出

### ISSUE THREAD

**Issue by Hasson-Wong** [fantasticit/think#225]
## 1. 问题的表现是怎样的？

0|@think/server  | [think] 消息服务启动成功
0|@think/server  | [think] 文档版本服务启动成功
0|@think/server  | [think] 验证码服务启动成功
0|@think/server  | Validation failed: 知识库描述至少3个字符
0|@think/server  | [onDisconnect] Server shutdown in progress
0|@think/server  | /app/node_modules/.pnpm/typeorm@0.2.41_ioredis@5.0.1+mysql2@2.3.3/node_modules/typeorm/error/TypeORMError.js:9
0|@think/server  |         var _this = _super.call(this, message) || this;
0|@think/server  |                            ^
0|@think/server  | QueryFailedError: Server shutdown in progress
0|@think/server  |     at QueryFailedError.TypeORMError [as constructor] (/app/node_modules/.pnpm/typeorm@0.2.41_ioredis@5.0.1+mysql2@2.3.3/node_modules/typeorm/error/TypeORMError.js:9:28)
0|@think/server  |     at new QueryFailedError (/app/node_modules/.pnpm/typeorm@0.2.41_ioredis@5.0.1+mysql2@2.3.3/node_modules/typeorm/error/QueryFailedError.js:13:28)
0|@think/server  |     at Query.onResult (/app/node_modules/.pnpm/typeorm@0.2.41_ioredis@5.0.1+mysql2@2.3.3/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:193:57)
0|@think/server  |     at Query.execute (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/commands/command.js:36:14)
0|@think/server  |     at PoolConnection.handlePacket (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:456:32)
0|@think/server  |     at PacketParser.onPacket (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:85:12)
0|@think/server  |     at PacketParser.executeStart (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/packet_parser.js:75:16)
0|@think/server  |     at Socket.<anonymous> (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:92:25)
0|@think/server  |     at Socket.emit (node:events:513:28)
0|@think/server  |     at addChunk (node:internal/streams/readable:324:12) {
0|@think/server  |   query: 'SELECT `DocumentEntity`.`id` AS `DocumentEntity_id`, `DocumentEntity`.`organizationId` AS `DocumentEntity_organizationId`, `DocumentEntity`.`wikiId` AS `DocumentEntity_wikiId`, `DocumentEntity`.`isWikiHome` AS `DocumentEntity_isWikiHome`, `DocumentEntity`.`createUserId` AS `DocumentEntity_createUserId`, `DocumentEntity`.`parentDocumentId` AS `DocumentEntity_parentDocumentId`, `DocumentEntity`.`title` AS `DocumentEntity_title`, `DocumentEntity`.`content` AS `DocumentEntity_content`, `DocumentEntity`.`state` AS `DocumentEntity_state`, `DocumentEntity`.`status` AS `DocumentEntity_status`, `DocumentEntity`.`sharePassword` AS `DocumentEntity_sharePassword`, `DocumentEntity`.`views` AS `DocumentEntity_views`, `DocumentEntity`.`index` AS `DocumentEntity_index`, `DocumentEntity`.`createdAt` AS `DocumentEntity_createdAt`, `DocumentEntity`.`updatedAt` AS `DocumentEntity_updatedAt` FROM `document` `DocumentEntity` WHERE `DocumentEntity`.`id` IN (?)',
0|@think/server  |   parameters: [ 'Yh-WRrl-3Eyb' ],
0|@think/server  |   driverError: Error: Server shutdown in progress
0|@think/server  |       at Packet.asError (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/packets/packet.js:728:17)
0|@think/server  |       at Query.execute (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/commands/command.js:29:26)
0|@think/server  |       at PoolConnection.handlePacket (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:456:32)
0|@think/server  |       at PacketParser.onPacket (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:85:12)
0|@think/server  |       at PacketParser.executeStart (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/packet_parser.js:75:16)
0|@think/server  |       at Socket.<anonymous> (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:92:25)
0|@think/server  |       at Socket.emit (node:events:513:28)
0|@think/server  |       at addChunk (node:internal/streams/readable:324:12)
0|@think/server  |       at readableAddChunk (node:internal/streams/readable:297:9)
0|@think/server  |       at Readable.push (node:internal/streams/readable:234:10) {
0|@think/server  |     code: 'ER_SERVER_SHUTDOWN',
0|@think/server  |     errno: 1053,
0|@think/server  |     sqlState: '08S01',
0|@think/server  |     sqlMessage: 'Server shutdown in progress',
0|@think/server  |     sql: "SELECT `DocumentEntity`.`id` AS `DocumentEntity_id`, `DocumentEntity`.`organizationId` AS `DocumentEntity_organizationId`, `DocumentEntity`.`wikiId` AS `DocumentEntity_wikiId`, `DocumentEntity`.`isWikiHome` AS `DocumentEntity_isWikiHome`, `DocumentEntity`.`createUserId` AS `DocumentEntity_createUserId`, `DocumentEntity`.`parentDocumentId` AS `DocumentEntity_parentDocumentId`, `DocumentEntity`.`title` AS `DocumentEntity_title`, `DocumentEntity`.`content` AS `DocumentEntity_content`, `DocumentEntity`.`state` AS `DocumentEntity_state`, `DocumentEntity`.`status` AS `DocumentEntity_status`, `DocumentEntity`.`sharePassword` AS `DocumentEntity_sharePassword`, `DocumentEntity`.`views` AS `DocumentEntity_views`, `DocumentEntity`.`index` AS `DocumentEntity_index`, `DocumentEntity`.`createdAt` AS `DocumentEntity_createdAt`, `DocumentEntity`.`updatedAt` AS `DocumentEntity_updatedAt` FROM `document` `DocumentEntity` WHERE `DocumentEntity`.`id` IN ('Yh-WRrl-3Eyb')"
0|@think/server  |   },
0|@think/server  |   code: 'ER_SERVER_SHUTDOWN',
0|@think/server  |   errno: 1053,
0|@think/server  |   sqlState: '08S01',
0|@think/server  |   sqlMessage: 'Server shutdown in progress',
0|@think/server  |   sql: "SELECT `DocumentEntity`.`id` AS `DocumentEntity_id`, `DocumentEntity`.`organizationId` AS `DocumentEntity_organizationId`, `DocumentEntity`.`wikiId` AS `DocumentEntity_wikiId`, `DocumentEntity`.`isWikiHome` AS `DocumentEntity_isWikiHome`, `DocumentEntity`.`createUserId` AS `DocumentEntity_createUserId`, `DocumentEntity`.`parentDocumentId` AS `DocumentEntity_parentDocumentId`, `DocumentEntity`.`title` AS `DocumentEntity_title`, `DocumentEntity`.`content` AS `DocumentEntity_content`, `DocumentEntity`.`state` AS `DocumentEntity_state`, `DocumentEntity`.`status` AS `DocumentEntity_status`, `DocumentEntity`.`sharePassword` AS `DocumentEntity_sharePassword`, `DocumentEntity`.`views` AS `DocumentEntity_views`, `DocumentEntity`.`index` AS `DocumentEntity_index`, `DocumentEntity`.`createdAt` AS `DocumentEntity_createdAt`, `DocumentEntity`.`updatedAt` AS `DocumentEntity_updatedAt` FROM `document` `DocumentEntity` WHERE `DocumentEntity`.`id` IN ('Yh-WRrl-3Eyb')"
0|@think/server  | }
0|@think/server  | Node.js v18.13.0
PM2              | App [@think/server:0] exited with code [1] via signal [SIGINT]
PM2              | App [@think/server:0] starting in -fork mode-
PM2              | App [@think/server:0] online
0|@think/server  | > @think/server@0.0.1 start
0|@think/server  | > cross-env NODE_ENV=production node dist/main
0|@think/server  | [Nest] 205  - 02/02/2023, 5:10:26 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
0|@think/server  | Error: connect ECONNREFUSED 172.18.0.3:3306
0|@think/server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)
0|@think/server  | [think] 访问记录服务启动错误: "getaddrinfo EAI_AGAIN redis-for-think"
## 2. 问题的复现路径
出现一次未进行复现
## 3. 预期是什么？
限制内容应不下发配置，并给出用户提示

**Comment by Hasson-Wong** [comment]
版本：241bcab7f92e0ad505baea6d6b31254f220f10dd
