### ISSUE TITLE
[BUG]运行报错 - Invalid default value for 'title'

### ISSUE THREAD

**Issue by qinxh** [fantasticit/think#250]
## 1. 问题的表现是怎样的？
按照文档使用docker打包部署，容器启动后，日志中报错：Invalid default value for 'title'
## 2. 问题的复现路径
1. 按照文档新建了 prod.yml，其中配置确认无误
2. docker build
3. docker run
4. 日志报错如下：
```
0|@think/server  | [Nest] 95  - 07/10/2023, 9:27:46 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
0|@think/server  | QueryFailedError: Invalid default value for 'title'
0|@think/server  |     at QueryFailedError.TypeORMError [as constructor] (/app/node_modules/.pnpm/typeorm@0.2.41_ioredis@5.0.1_mysql2@2.3.3/node_modules/typeorm/error/TypeORMError.js:9:28)
0|@think/server  |     at new QueryFailedError (/app/node_modules/.pnpm/typeorm@0.2.41_ioredis@5.0.1_mysql2@2.3.3/node_modules/typeorm/error/QueryFailedError.js:13:28)
0|@think/server  |     at Query.onResult (/app/node_modules/.pnpm/typeorm@0.2.41_ioredis@5.0.1_mysql2@2.3.3/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:193:57)
0|@think/server  |     at Query.execute (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/commands/command.js:36:14)
0|@think/server  |     at PoolConnection.handlePacket (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:456:32)
0|@think/server  |     at PacketParser.onPacket (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:85:12)
0|@think/server  |     at PacketParser.executeStart (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/packet_parser.js:75:16)
0|@think/server  |     at Socket.<anonymous> (/app/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:92:25)
0|@think/server  |     at Socket.emit (node:events:513:28)
0|@think/server  |     at addChunk (node:internal/streams/readable:324:12)
```
## 3. 预期是什么？
看上去是数据库问题，请问使用哪个版本的mysql可以启用运行，目前我使用的版本是：5.7.36

**Comment by hzbb2221** [comment]
我的数据库版本是8.0.27，应该跟mysql版本无关，看着更像是数据库连接信息配置错误

**Comment by fantasticit** [comment]
`docker run -d --restart=always --name mysql-for-think-dev -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=think -e MYSQL_PASSWORD=think -e MYSQL_DATABASE=think mysql:5.7 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
`

试一下这个 docker 命令启动一个数据库，连这个数据库试一下来排查下是不是数据库问题。如果不是数据库问题，提供完善的错误信息再看下。

**Comment by slowlydd** [comment]
手动创建数据库，同样遇到了这个问题，是字符编码的问题，注意数据库的字符编码 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
