### ISSUE TITLE
[BUG] docker-compose部署报错think容器报错

### ISSUE THREAD

**Issue by yuerspring** [fantasticit/think#283]
|@think/client | Error: Could not find a production build in the '/app/packages/client/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id  
161|@think/client | at NextNodeServer.getBuildId (/app/node_modules/.pnpm/next@12.1.0_@babel+core@7.24.7_react-dom@17.0.2_react@17.0.2__react@17.0.2_sass@1.77.6/node_modules/next/dist/server/next-server.js:126:23)  
171|@think/client | at new Server (/app/node_modules/.pnpm/next@12.1.0_@babel+core@7.24.7_react-dom@17.0.2_react@17.0.2__react@17.0.2_sass@1.77.6/node_modules/next/dist/server/base-server.js:92:29)  
181|@think/client | at new NextNodeServer (/app/node_modules/.pnpm/next@12.1.0_@babel+core@7.24.7_react-dom@17.0.2_react@17.0.2__react@17.0.2_sass@1.77.6/node_modules/next/dist/server/next-server.js:74:9)  
191|@think/client | at NextServer.createServer (/app/node_modules/.pnpm/next@12.1.0_@babel+core@7.24.7_react-dom@17.0.2_react@17.0.2__react@17.0.2_sass@1.77.6/node_modules/next/dist/server/next.js:111:16)  
201|@think/client | at async /app/node_modules/.pnpm/next@12.1.0_@babel+core@7.24.7_react-dom@17.0.2_react@17.0.2__react@17.0.2_sass@1.77.6/node_modules/next/dist/server/next.js:123:31  
21PM2 | App [@think/client:1] exited with code [1] via signal [SIGINT]

**Comment by tboy2015** [comment]
解决了吗

**Comment by yuerspring** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
